# Generated by Django 5.1.4 on 2024-12-09 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='book',
        ),
    ]
