# Generated by Django 5.1.4 on 2024-12-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0005_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed_by',
            field=models.ManyToManyField(related_name='borrowed_books', to='library_api.patronprofile'),
        ),
    ]
