# Generated by Django 5.1.4 on 2026-05-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_api', '0007_borrowrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
    ]
